class Config25 {

    final Map<String, Map<String, ?>> buildConfigurations = [
        x64Mac    : [
                os                  : 'mac',
                arch                : 'x64',
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.mac',
                additionalTestLabels: '!sw.os.osx.10_15',
                test                : false,
                configureArgs       : '--enable-dtrace --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        x64Linux  : [
                os                  : 'linux',
                arch                : 'x64',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
                dockerNode          : 'sw.tool.docker',
                test                : false,
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'hw.arch.x86 && sw.os.linux',
                configureArgs       : '--enable-dtrace --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        x64Windows: [
                os                  : 'windows',
                arch                : 'x64',
                additionalNodeLabels: 'EBC:os=windows,arch=x86-64,distro=windows2025',
                cleanWorkspaceAfterBuild: true,
                test                : false,
                configureArgs       : '--with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition" --with-jdk-rc-name="IBM Semeru Runtime"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        ppc64Aix    : [
                os                  : 'aix',
                arch                : 'ppc64',
                additionalNodeLabels: 'hw.arch.ppc64 && sw.os.aix.7_2 && sw.tool.c++runtime.17_1',
                test                : false,
                cleanWorkspaceAfterBuild: true,
                configureArgs       : '--disable-ccache --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        s390xLinux    : [
                os                  : 'linux',
                arch                : 's390x',
                test                : false,
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.s390x',
                dockerImage: 'runtimes/ibm-java-8/s390x-redhat7:gcc14_semeru',
                dockerRegistry: 'https://icr.io/',
                dockerCredential : 'ea4b3e98-4334-48d4-8211-98deb8767b55',
                dockerNode : 'sw.tool.docker',
                configureArgs       : '--with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        ppc64leLinux    : [
                os                  : 'linux',
                arch                : 'ppc64le',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
                dockerNode         : 'sw.tool.docker',
                test                : false,
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.ppc64le && sw.os.linux',
                configureArgs       : '--with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        aarch64Linux    : [
                os                  : 'linux',
                arch                : 'aarch64',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerNode          : 'sw.tool.docker',
                additionalNodeLabels: 'hw.arch.aarch64 && sw.os.linux',
                test                : false,
                configureArgs       : '--enable-dtrace --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                cleanWorkspaceAfterBuild : true,
                buildArgs           : '--create-jre-image --ssh'
        ],

        aarch64Mac: [
                os                  : 'mac',
                arch                : 'aarch64',
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.aarch64 && sw.os.mac',
                cleanWorkspaceAfterBuild: true,
                test                : false,
                configureArgs       : '--enable-dtrace --disable-warnings-as-errors --with-noncompressedrefs --with-product-name="IBM Semeru Runtime" --with-product-suffix="Open Edition"',
                buildArgs           : '--create-jre-image --ssh'
        ],

        x64MacIBM    : [
                os                  : 'mac',
                arch                : 'x64',
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.x86 && sw.os.mac',
                additionalTestLabels: '!sw.os.osx.10_15',
                test                : 'default',
                configureArgs       : '--enable-dtrace',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        x64LinuxIBM  : [
                os                  : 'linux',
                arch                : 'x64',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
                dockerNode          : 'sw.tool.docker',
                test                : [
                    weekly : [
                        "sanity.external",
                        "sanity.functional",
                        "sanity.jck",
                        "sanity.jck.fips140_2",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.jck.OpenJCEPlus",
                        "sanity.openjdk",
                        "sanity.openjdk.fips140_2",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.openjdk.OpenJCEPlus",
                        "sanity.perf",
                        "sanity.system",
                        "extended.functional",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.functional.OpenJCEPlus",
                        "extended.jck",
                        "extended.jck.fips140_2",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.jck.OpenJCEPlus",
                        "extended.openjdk",
                        "extended.openjdk.fips140_2",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.openjdk.OpenJCEPlus",
                        "extended.perf",
                        "extended.system",
                        "special.functional",
                        "special.jck",
                        "special.jck.fips140_2",
                        "special.jck.fips140_3_OpenJCEPlusFIPS",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "special.jck.OpenJCEPlus",
                        "special.openjdk",
                        "special.system",
                        "dev.external",
                        "dev.functional",
                        "dev.openjdk"
                    ]
                ],
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'hw.arch.x86 && sw.os.linux',
                configureArgs       : '--enable-dtrace',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        x64WindowsIBM: [
                os                  : 'windows',
                arch                : 'x64',
                additionalNodeLabels: 'EBC:os=windows,arch=x86-64,distro=windows2025',
                cleanWorkspaceAfterBuild: true,
                test                : 'default',
                configureArgs       : '--with-jdk-rc-name="IBM Semeru Runtime"',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        ppc64AixIBM    : [
                os                  : 'aix',
                arch                : 'ppc64',
                additionalNodeLabels: 'hw.arch.ppc64 && sw.os.aix.7_2 && sw.tool.c++runtime.17_1',
                test                : 'default',
                cleanWorkspaceAfterBuild: true,
                configureArgs       : '--disable-ccache',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        s390xLinuxIBM    : [
                os                  : 'linux',
                arch                : 's390x',
                test                : [
                    weekly : [
                        "sanity.external",
                        "sanity.functional",
                        "sanity.jck",
                        "sanity.jck.fips140_2",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.jck.OpenJCEPlus",
                        "sanity.openjdk",
                        "sanity.openjdk.fips140_2",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.openjdk.OpenJCEPlus",
                        "sanity.perf",
                        "sanity.system",
                        "extended.functional",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.functional.OpenJCEPlus",
                        "extended.jck",
                        "extended.jck.fips140_2",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.jck.OpenJCEPlus",
                        "extended.openjdk",
                        "extended.openjdk.fips140_2",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.openjdk.OpenJCEPlus",
                        "extended.perf",
                        "extended.system",
                        "special.functional",
                        "special.jck",
                        "special.jck.fips140_2",
                        "special.jck.fips140_3_OpenJCEPlusFIPS",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "special.jck.OpenJCEPlus",
                        "special.openjdk",
                        "special.system",
                        "dev.external",
                        "dev.functional",
                        "dev.openjdk"
                    ]
                ],
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.s390x',
                dockerImage: 'runtimes/ibm-java-8/s390x-redhat7:gcc14_semeru',
                dockerRegistry: 'https://icr.io/',
                dockerCredential : 'ea4b3e98-4334-48d4-8211-98deb8767b55',
                dockerNode : 'sw.tool.docker',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        ppc64leLinuxIBM    : [
                os                  : 'linux',
                arch                : 'ppc64le',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerFile          : 'pipelines/build/dockerFiles/cuda.dockerfile',
                dockerNode         : 'sw.tool.docker',
                test                : [
                    weekly : [
                        "sanity.external",
                        "sanity.functional",
                        "sanity.jck",
                        "sanity.jck.fips140_2",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.jck.OpenJCEPlus",
                        "sanity.openjdk",
                        "sanity.openjdk.fips140_2",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.openjdk.OpenJCEPlus",
                        "sanity.perf",
                        "sanity.system",
                        "extended.functional",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.functional.OpenJCEPlus",
                        "extended.jck",
                        "extended.jck.fips140_2",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.jck.OpenJCEPlus",
                        "extended.openjdk",
                        "extended.openjdk.fips140_2",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.openjdk.OpenJCEPlus",
                        "extended.perf",
                        "extended.system",
                        "special.functional",
                        "special.jck",
                        "special.jck.fips140_2",
                        "special.jck.fips140_3_OpenJCEPlusFIPS",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "special.jck.OpenJCEPlus",
                        "special.openjdk",
                        "special.system",
                        "dev.external",
                        "dev.functional",
                        "dev.openjdk"
                    ]
                ],
                cleanWorkspaceAfterBuild: true,
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.ppc64le && sw.os.linux',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        aarch64LinuxIBM    : [
                os                  : 'linux',
                arch                : 'aarch64',
                dockerImage         : 'ghcr.io/adoptium/adoptium_build_image:centos7',
                dockerRegistry      : 'https://ghcr.io/',
                dockerCredential    : 'f5a0bd2f-093e-41ea-bd6f-875936334a63',
                dockerNode          : 'sw.tool.docker',
                additionalNodeLabels: 'hw.arch.aarch64 && sw.os.linux',
                test                : [
                    weekly : [
                        "sanity.external",
                        "sanity.functional",
                        "sanity.jck",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.jck.OpenJCEPlus",
                        "sanity.openjdk",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "sanity.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "sanity.openjdk.OpenJCEPlus",
                        "sanity.perf",
                        "sanity.system",
                        "extended.functional",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.functional.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.functional.OpenJCEPlus",
                        "extended.jck",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.jck.OpenJCEPlus",
                        "extended.openjdk",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "extended.openjdk.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "extended.openjdk.OpenJCEPlus",
                        "extended.perf",
                        "extended.system",
                        "special.functional",
                        "special.jck",
                        "special.jck.fips140_3_OpenJCEPlusFIPS",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3",
                        "special.jck.fips140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced",
                        "special.jck.OpenJCEPlus",
                        "special.openjdk",
                        "special.system",
                        "dev.external",
                        "dev.functional",
                        "dev.openjdk"
                    ]
                ],
                configureArgs       : '--enable-dtrace',
                cleanWorkspaceAfterBuild : true,
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ],

        aarch64MacIBM: [
                os                  : 'mac',
                arch                : 'aarch64',
                additionalNodeLabels: 'ci.project.openj9 && hw.arch.aarch64 && sw.os.mac',
                cleanWorkspaceAfterBuild: true,
                test                : 'default',
                configureArgs       : '--enable-dtrace --disable-warnings-as-errors --with-noncompressedrefs',
                additionalFileNameTag: 'IBM',
                buildArgs           : '--create-jre-image --ssh --disable-adopt-branch-safety -r git@github.ibm.com:runtimes/openj9-openjdk-jdk25 -b ibm_sdk'
        ]
  ]

}

Config25 config = new Config25()
return config.buildConfigurations
